services:
  feedgen:
    build: .
    restart: always
    volumes:
      - './db.sqlite:/app/db.sqlite'
    environment:
      - 'FEEDGEN_SQLITE_LOCATION="db.sqlite"'
      - 'FEEDGEN_HOSTNAME="bsky.danae.link"'
      - 'FEEDGEN_PUBLISHER_DID="did:plc:eezzekyc5lfabmza2qvrjxc5"'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.audune-nextcloud.rule=Host(`bsky.danae.link`)'
      - 'traefik.http.routers.audune-nextcloud.entrypoints=http_public'
      - 'traefik.http.routers.audune-nextcloud.priority=200'
